export const copy = {
  nav: {
    home: '首页',
    projects: '项目',
    experience: '经历',
    honors: '荣誉',
    timeline: '时间线',
    chat: '问问 AI',
    resume: '下载简历',
    sales: '联系合作',
  },
  home: {
    projects: '精选项目',
    experience: '实践经历',
    honors: '荣誉与特质',
    education: '教育',
    timeline: '时间线',
    trusted: '常用技术与合作语境',
    heroHint: '面向研究与工程的作品集',
    menuHint: 'Portfolio',
    deskTitle: '廖晨扬 — Profile',
    deskCompose: '问问晨扬',
    deskNav: {
      overview: '概览',
      projects: '项目',
      experience: '经历',
      honors: '荣誉',
      education: '教育',
      timeline: '时间线',
    },
    labels: '焦点',
    search: '搜索作品与经历',
    summaryBy: '摘要',
    triageEyebrow: 'Focus',
    triageTag: 'AI-native',
    triageTitleA: '把研究与工程',
    triageTitleB: '收进同一条主线。',
    triageBody:
      '从大模型机器遗忘到多智能体编排，再落到可上线的全栈系统。主页按信号强度整理履历，而不是堆砌清单。',
    chips: ['LLM Unlearning', 'Multi-Agent', 'Full-stack', 'Quant Systems'],
    ctaTitleA: '关掉无关标签页。',
    ctaTitleB: '打开今天的主线。',
    ctaBody: '想了解项目细节、研究思路或合作意向，直接问 AI，或下载最新简历。',
    downloadNote: 'PDF · 中文版',
  },
  detail: {
    overview: '概览',
    highlights: '亮点',
    metrics: '成果',
    stack: '技术栈',
    previous: '上一篇',
    next: '下一篇',
    back: '返回首页',
  },
  chat: {
    title: '问问廖晨扬',
    subtitle: '了解项目、经历与研究方向',
    placeholder: '输入你的问题…',
    send: '发送',
    history: '历史会话',
    fresh: '新会话',
    empty: '可以问我：他在研究什么？',
  },
  common: {
    loading: '加载中…',
    notFound: '没有找到内容',
    open: '查看详情',
    present: '至今',
    menu: '菜单',
  },
} as const;
